// Generated by scripts/convert-clearurls-rules.mjs. Do not edit manually.
/* eslint-disable @stylistic/quote-props */

export interface ClearUrlsProviderRules {
  name: string;
  urlPattern: string;
  rules: string[];
  rawRules: string[];
  exceptions: string[];
}

export const CLEARURLS_GLOBAL_RULES = [];
