export const TRACKERS_BY_ROOT: Record<string, string[]> = {
  utm_: [
    'source',
    'medium',
    'term',
    'campaign',
    'content',
    'name',
    'cid',
    'reader',
    'viz_id',
    'pubreferrer',
    'swu',
  ],
  IC: ['ID'],
  ic: ['id'],
  _hs: ['enc', 'mi'],
  mkt_: ['tok'],
  mc_: ['cid', 'eid'],
  ns_: ['source', 'mchannel', 'campaign', 'linkname', 'fee'],
  sr_: ['share'],
  vero_: ['conv', 'id'],
  '': [
    'fbclid',
    'igshid',
    'srcid',
    'gclid',
    'ocid',
    'ncid',
    'nr_email_referer',
    'ref',
    'spm',
    'si',
  ],
};

export const DOMAIN_TRACKERS: Record<string, string[]> = {
  google: [
    'source',
    'medium',
    'term',
    'campaign',
    'content',
    'name',
    'cid',
    'reader',
    'viz_id',
    'pubreferrer',
    'swu',
    'sca_esv',
    'sca_eid',
    'gs_lp',
    'gs_lpos',
    'sca_upv',
    'sca_uid',
    'newwindow',
    'ei',
    'ved',
    'oq',
    'sclient',
    'uact',
  ],
  tiktok: [
    'u_code',
    'preview_pb',
    '_d',
    'timestamp',
    'user_id',
    'share_app_name',
    'share_iid',
    'source',
  ],
  facebook: [
    'hc_[a-z_%\\[\\]0-9]*',
    '[a-z]*ref[a-z]*',
    '__tn__',
    'eid',
    '__(?:xts|cft)__(?:\\[|%5B)\\d(?:\\]|%5D)',
    'comment_tracking',
    'dti',
    'app',
    'video_source',
    'ftentidentifier',
    'pageid',
    'padding',
    'ls_ref',
    'action_history',
    'tracking',
    'referral_code',
    'referral_story_type',
    'eav',
    'sfnsn',
    'idorvanity',
    'wtsid',
    'rdc',
    'rdr',
    'paipv',
    '_nc_x',
    '_rdr',
    'mibextid',
  ],
  reddit: [
    '%24deep_link',
    '\\$deep_link',
    'correlation_id',
    'ref_campaign',
    'ref_source',
    '%243p',
    'rdt',
    '\\$3p',
    '%24original_url',
    '\\$original_url',
    '_branch_match_id',
  ],
  bing: ['cvid', 'form', 'sk', 'sp', 'sc', 'qs', 'qp'],
  instagram: ['igshid', 'igsh'],
  twitter: ['ref_src', 'ref_url', 'ref_src', 'ref_url'],
  linkedin: ['trk'],
  amazon: ['ascsubtag'],
  ebay: ['_trkparms', '_trksid', '_from', 'hash'],
  youtube: ['feature', 'gclid', 'kw', 'si'],
  github: ['email_token', 'email_source'],
  aliexpress: [
    'ws_ab_test',
    'btsid',
    'algo_expid',
    'algo_pvid',
    'gps-id',
    'scm[_a-z-]*',
    'cv',
    'af',
    'mall_affr',
    'sk',
    'dp',
    'terminal_id',
    'aff_request_id',
  ],
  bilibili: [
    'callback',
    'spm_id_from',
    'from_source',
    'from',
    'seid',
    'mid',
    'share_source',
    'msource',
    'refer_from',
    'share_from',
    'share_medium',
    'share_source',
    'share_plat',
    'share_tag',
    'share_session_id',
    'timestamp',
    'unique_k',
    'vd_source',
    'plat_id',
    'buvid',
    'is_story_h5',
    'up_id',
    'bbid',
    'ts',
  ],
};

export const ALL_TRACKERS: string[] = Object.entries(TRACKERS_BY_ROOT).flatMap(
  ([root, suffixes]) => suffixes.map((suffix) => root + suffix),
);
